-- AI Fitness Coach: Supabase database schema
-- Run this file in Supabase SQL Editor.

begin;

create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise text not null,
  side text not null check (side in ('Left', 'Right', 'Both')),
  reps_left integer not null default 0 check (reps_left >= 0),
  reps_right integer not null default 0 check (reps_right >= 0),
  duration double precision not null default 0 check (duration >= 0),
  set_number integer not null default 1 check (set_number >= 1),
  target_reps integer not null default 10 check (target_reps >= 1),
  timestamp timestamptz not null default now()
);

create index if not exists workout_logs_user_id_idx
  on public.workout_logs (user_id);

create index if not exists workout_logs_timestamp_idx
  on public.workout_logs (timestamp desc);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  age integer check (age between 5 and 120),
  gender text,
  height_cm integer check (height_cm between 50 and 300),
  weight_kg integer check (weight_kg between 20 and 400),
  body_type text,
  activity_level text,
  goal_type text,
  diet_type text,
  experience_level text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at();

alter table public.workout_logs enable row level security;
alter table public.user_profiles enable row level security;

drop policy if exists "workout_logs_select_own" on public.workout_logs;
create policy "workout_logs_select_own"
on public.workout_logs
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "workout_logs_insert_own" on public.workout_logs;
create policy "workout_logs_insert_own"
on public.workout_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "workout_logs_update_own" on public.workout_logs;
create policy "workout_logs_update_own"
on public.workout_logs
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "workout_logs_delete_own" on public.workout_logs;
create policy "workout_logs_delete_own"
on public.workout_logs
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_profiles_select_own" on public.user_profiles;
create policy "user_profiles_select_own"
on public.user_profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_profiles_insert_own" on public.user_profiles;
create policy "user_profiles_insert_own"
on public.user_profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_profiles_update_own" on public.user_profiles;
create policy "user_profiles_update_own"
on public.user_profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_profiles_delete_own" on public.user_profiles;
create policy "user_profiles_delete_own"
on public.user_profiles
for delete
to authenticated
using (auth.uid() = user_id);

commit;
